name: GoRelease

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write 

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Build Cross-Platform Binaries
      run: make all # Triggers windows, macos, and linux targets

    - name: Create Release and Upload Artifacts
      uses: softprops/action-gh-release@v2
      with:
        files: |
          vflat.exe
          vflat-macos
          vflat-linux
